<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/predictions_Through_scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

In [3]:
import pandas as pd

In [4]:
data = {
    "marks": [10,20,30,40,50,60,70,80,90,100],
"pass": [0,0,0,0,1,1,1,1,1,1]
}

In [5]:
df = pd.DataFrame(data)


In [6]:
x = df[["marks"]]
y = df["pass"]
print(x)
print("\n y-values\n")
print(y)

   marks
0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100

 y-values

0    0
1    0
2    0
3    0
4    1
5    1
6    1
7    1
8    1
9    1
Name: pass, dtype: int64


In [7]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2, random_state= 42)

In [8]:
print(y_train)

5    1
0    0
7    1
2    0
9    1
4    1
3    0
6    1
Name: pass, dtype: int64


In [9]:
model = XGBClassifier()

In [10]:
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [11]:
prediction = model.predict(x_train)
print(prediction)

[1 1 1 1 1 1 1 1]


In [13]:
model.predict([[1]])

array([1])

In [14]:
model.fit(x_train, y_train)

predictions = model.predict(x_test)

print("Actual:", y_test.values)
print("Predicted:", predictions)

Actual: [1 0]
Predicted: [1 1]


In [15]:
predictions = model.predict(x_test)
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print(accuracy)

0.5


In [16]:
print("X_test:")
print(x_test)

print("Actual:", y_test.values)
print("Predicted:", predictions)


X_test:
   marks
8     90
1     20
Actual: [1 0]
Predicted: [1 1]


In [17]:
print(model.predict_proba([[90]]))

[[0.375 0.625]]


In [18]:
print(model.predict_proba([[46]]))

[[0.375 0.625]]


In [19]:
print(model.classes_)

[0 1]


In [20]:
import pandas as pd
import numpy as np

np.random.seed(42)

cgpa = np.round(np.random.uniform(4.0, 10.0, 1000), 2)

# Passing rule with some randomness
pass_status = []

for c in cgpa:
    if c < 5.5:
        pass_status.append(np.random.choice([0, 1], p=[0.9, 0.1]))
    elif c < 6.5:
        pass_status.append(np.random.choice([0, 1], p=[0.5, 0.5]))
    else:
        pass_status.append(np.random.choice([0, 1], p=[0.1, 0.9]))

df = pd.DataFrame({
    "cgpa": cgpa,
    "pass": pass_status
})

print(df.head())
print("\nTotal Rows:", len(df))

   cgpa  pass
0  6.25     0
1  9.70     1
2  8.39     1
3  7.59     1
4  4.94     0

Total Rows: 1000


In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


In [22]:
x =df[["cgpa"]]
y  = df["pass"]
print(x)

     cgpa
0    6.25
1    9.70
2    8.39
3    7.59
4    4.94
..    ...
995  4.55
996  9.50
997  4.82
998  9.70
999  6.68

[1000 rows x 1 columns]


In [23]:
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size = 0.2,random_state=42)


In [24]:
model = LogisticRegression()

In [25]:
model.fit(x_train , y_train)

LogisticRegression()

In [26]:
print(model.predict(df[["cgpa"]]))
print(model.predict_proba(df[["cgpa"]]))

[1 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0
 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 1 1 0 0 1
 1 1 1 0 1 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 0 1 1 0 0 0
 0 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0 1 0 0 0 1 1
 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0 1 1 1 0 0 0 1 1 0
 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 0 0 1 1 1 0 1 0 0 1 1 1 1 1
 0 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1
 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 0 0 1 1 0 1
 1 0 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0
 0 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1
 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 0 0 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 0 1 1 1 1
 1 1 1 1 1 0 0 1 1 1 1 0 

In [27]:
from sklearn.metrics import confusion_matrix

In [ ]:
y_pred = model.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 62  19]
 [ 14 105]]


In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.77      0.79        81
           1       0.85      0.88      0.86       119

    accuracy                           0.83       200
   macro avg       0.83      0.82      0.83       200
weighted avg       0.83      0.83      0.83       200

