<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install torch

In [4]:
import torch

In [7]:
print(torch.__version__)

2.11.0+cpu


In [10]:
c = torch.tensor([[12,12,12],[121,12,12]])

In [11]:
c

tensor([[ 12,  12,  12],
        [121,  12,  12]])

In [13]:
c.dtype

torch.int64

In [14]:
print(c.shape)
print(c.dtype)
print(c.ndim)

torch.Size([2, 3])
torch.int64
2


In [16]:
print(torch.zeros(3,4))

print(torch.ones(2,3))

torch.rand(3,3)

torch.randn(3,3)

torch.eye(4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [17]:
tensor = torch.tensor([1,2,3])

arr = tensor.numpy()

print(arr)

[1 2 3]
