<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

In [2]:
import torch

In [3]:
print(torch.__version__)

2.11.0+cpu


In [4]:
c = torch.tensor([[12,12,12],[121,12,12]])

In [5]:
c

tensor([[ 12,  12,  12],
        [121,  12,  12]])

In [6]:
c.dtype

torch.int64

In [7]:
print(c.shape)
print(c.dtype)
print(c.ndim)

torch.Size([2, 3])
torch.int64
2


In [8]:
print(torch.zeros(3,4))

print(torch.ones(2,3))

torch.rand(3,3)

torch.randn(3,3)

torch.eye(4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [9]:
tensor = torch.tensor([1,2,3])

arr = tensor.numpy()

print(arr)

[1 2 3]


In [10]:
x = torch.tensor([1100])

In [11]:
x

tensor([1100])

In [12]:
x = torch.tensor([1,2,3])

y = torch.tensor([4,5,6])

print(x+y)

print(x-y)

print(x*y)

print(x/y)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [13]:
A = torch.tensor([[1,2],
                  [3,4]])

B = torch.tensor([[5,6],
                  [7,8]])

print(torch.matmul(A,B))

tensor([[19, 22],
        [43, 50]])


In [14]:
A @ B

tensor([[19, 22],
        [43, 50]])

In [15]:
x = torch.tensor([[1,2,3],
                  [4,5,6]])

print(x[0])

print(x[1])

print(x[:,1])

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([2, 5])


In [16]:
torch.cuda.is_available()

False

In [17]:
x = torch.tensor(2.0, requires_grad=True)

y = x**2

y.backward()

print(x.grad)

tensor(4.)


In [18]:
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)
